### ISSUE TITLE
Introduce an init container to manage secrets

### ISSUE THREAD

**Issue by ndeloof** [docker/ecs-plugin#207]
ECS only support secret binding as environment variables. To offer an homogeneous docker experience, we will replicate the "secret as bind mount" solution using an init container.

- [ ] Task with bound secret(s) is created with an init container, sharing `/run/secrets/` volume with main container. 
- [ ] Secret's Init container is set to inject secret value as environment, and command will dump environment variable into  `/run/secrets/<secret_name>`
- [ ] Secret's Init container is configured as essential=false so that it can terminate without blocking deployment (we will need a workaround for https://github.com/awslabs/goformation/issues/61#issuecomment-625139607 :'( )
- [ ] Main container is configured to depend on init container

**Comment by ndeloof** [comment]
There's a mismatch between Docker secrets model and Amazon Secret Manager:
- Docker secrets as plain string, injected in a named file under `/run/secrets`. So secret "foo" with value "bar" will result in file `/run/secrets/foo` with content `bar`
- AWS allows a set of `key:value` entries as secret content.

Possible approaches:
- allow user to declare AWS secrets ARN in compose file, which would result in an implicit set of secrets to be bound "the docker way"
- inject AWS secrets into container as `/run/secret/name`, and let application code read this file as a json key:value set.
- any other option ?

**Comment by ndeloof** [comment]
same issue applies to Kubernetes
https://github.com/docker/compose-on-kubernetes/blob/master/docs/mapping.md#secrets

**Comment by ndeloof** [comment]
Proposal:

assuming AWS Secret manager is set with secret `foo_bar` containing `{"foo":"bar"}` key:value pair (and potentially more entries)
with compose file:
```yaml

  backend:
    image: ndeloof/backend
    secrets:
      - foo

secrets:
  foo:
    name: "arn:aws:secretsmanager:eu-west-3:123:secret:foo_bar"
    external: true
```

ECS integration can retrieve secret from Secret Manager based on ARN, lookup `foo` key inside retrieved secret (foo being compose secret's name) and inject value into container as `/run/secret/foo` with content `bar`

**Comment by justincormack** [comment]
I was thinking supporting scopes, say that secret foo_bar contains keys foo and baz
```
  backend:
    image: ndeloof/backend
    secrets:
      - foobar/foo
      - foobar/baz

secrets:
  foobar:
    name: "arn:aws:secretsmanager:eu-west-3:123:secret:foo_bar"
    external: true
```

Looking at the docs though, secret manager is just storing a string, but it is often (recommendation) JSON with keys and values, but thats not required. https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html

**Comment by ndeloof** [comment]
The API indeed allows to create raw string secrets in secret manager, but the web console clearly expect key+value pairs

Not on @justincormack proposal: using `foobar/foo` as a scope alias to target a sub-element within foobar secret require changes to the compose spec. service.secrets is expected to refer to elements in the top-level `secrets` dictionary.

Alternative proposal:
bind secrets from AWS Secret manager as subfolders inside `/run/secret/`, i.e

```yaml
  backend:
    image: ndeloof/backend
    secrets:
      - my_secrets

secrets:
  my_secrets:
    name: "arn:aws:secretsmanager:eu-west-3:123:secret:foo_bar"
    external: true
```
will resutl into `/run/secrets/my_secrets/foo` file injected into container with content `bar`, same for other keys in the AWS secret
